# SPDX-License-Identifier: Apache-2.0 OR MIT

version = 3
SPDX-PackageName = "spz"
SPDX-PackageSupplier = "SPZ Developers (AUTHORS.md OR .mailmap)"
SPDX-PackageDownloadLocation = "https://github.com/Jackneill/spz"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
