# SPDX-License-Identifier: Apache-2.0 OR MIT

version = 3
SPDX-PackageName = "spz"
SPDX-PackageSupplier = "SPZ Authors (AUTHORS.md OR .mailmap)"
SPDX-PackageDownloadLocation = "https://github.com/Jackneill/spz"

[[annotations]]
path = ["**/*"]
SPDX-FileCopyrightText = "SPZ Authors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
