unstable_features = false

version = "Two"

edition = "2024"
hard_tabs = true
tab_spaces = 8
max_width = 100
newline_style = "Unix"

binop_separator = "Front"
brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
error_on_unformatted = true
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
imports_indent = "Block"
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
merge_imports = true
group_imports = "StdExternalCrate"
indent_style = "Block"
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
#normalize_doc_attributes = true # buggy on nightly
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
use_field_init_shorthand = false
where_single_line = false
wrap_comments = false
