name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  python-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Python Lint
        run: just py-lint

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Lint
        run: just lint

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Build
        run: just build

  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Install cargo audit
        run: |
          cargo install cargo-audit

      - name: Security
        run: just security

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Test
        run: just test

  bench:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Bench
        run: just bench
