name: Rust CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_call: # from ./release.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Lint
        run: just lint

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Build
        run: just build

  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo deny
        run: |
          cargo install cargo-deny

      - name: Install cargo audit
        run: |
          cargo install cargo-audit

      - name: Security
        run: just security

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Test
        run: just test

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Install calc
        run: |
          sudo apt install -y calc

      - name: Install cargo fuzz
        run: |
          cargo install cargo-fuzz

      - name: Fuzz
        run: just fuzz

      - name: Upload fuzz results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  bench:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: extractions/setup-just@v3
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Bench
        run: just bench
